In [12]:
import pandas as pd

df = pd.read_csv("/content/100_Unique_QA_Dataset.csv")

df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [13]:
# Tokenize

def tokenize(text):
  text = text.lower()
  text = text.replace('?','')
  text = text.replace("'","")
  return text.split()

In [14]:
tokenize("Hello my name is vamshi")

['hello', 'my', 'name', 'is', 'vamshi']

In [15]:
vocab = {'<UNK>':0} # Total unique words  #<unk>->unknown

In [16]:
def build_vocab(row):
  tokenized_question = tokenize(row['question'])
  tokenzied_answer = tokenize(row['answer'])

  merged_tokens = tokenized_question + tokenzied_answer

  for token in merged_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

In [17]:
df.apply(build_vocab, axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [18]:
len(vocab)

324

In [ ]:
vocab

In [21]:
#Convert words to numerical indices

def text_to_indices(text, vocab):

  indexed_text = []

  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])
  return indexed_text

In [22]:
text_to_indices("my name is vamshi", vocab)

[0, 0, 2, 0]

In [23]:
import torch
from torch.utils.data import Dataset, DataLoader

In [26]:
class QADataSet(Dataset):

  def __init__(self, df, vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]


  def __getitem__(self, index):

    numerical_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [27]:
dataset = QADataSet(df, vocab)

In [28]:
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

In [41]:
torch.manual_seed(42)
for question, answer in dataloader:
  print(f"question: {question}, answer: {answer[0]}")

question: tensor([[  1,   2,   3,  17, 115,  83,  84]]), answer: tensor([116])
question: tensor([[ 10, 308,   3, 309, 310]]), answer: tensor([311])
question: tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]]), answer: tensor([244])
question: tensor([[ 1,  2,  3,  4,  5, 73]]), answer: tensor([74])
question: tensor([[ 10,  96,   3, 104, 239]]), answer: tensor([240])
question: tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]]), answer: tensor([155])
question: tensor([[78, 79, 80, 81, 82, 83, 84]]), answer: tensor([85])
question: tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]), answer: tensor([199])
question: tensor([[10, 96,  3, 97]]), answer: tensor([98])
question: tensor([[ 42, 137,   2, 138,  39, 175, 269]]), answer: tensor([99])
question: tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]), answer: tensor([28])
question: tensor([[  1,   2,   3,  33,  34,   5, 245]]), answer: tensor([246])
question: tensor([[  1,   2,   3,  37,  38,  39, 161]]), answer: tensor([162])
question: tensor([[  1,  87, 229, 230, 231, 232]]), answer: tensor([233])
question: tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]), answer: tensor([205])
question: tensor([[ 78,  79, 261, 151,  14, 262, 153]]), answer: tensor([36])
question: tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]]), answer: tensor([173])
question: tensor([[  1,   2,   3, 234,   5, 235]]), answer: tensor([131])
question: tensor([[ 42, 167,   2,   3,  17, 168, 169]]), answer: tensor([170])
question: tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]]), answer: tensor([205])
question: tensor([[ 42, 137,   2, 138,  39, 139]]), answer: tensor([53])
question: tensor([[1, 2, 3, 4, 5, 6]]), answer: tensor([7])
question: tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]), answer: tensor([145])
question: tensor([[ 1,  2,  3,  4,  5, 99]]), answer: tensor([100])
question: tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]]), answer: tensor([121])
question: tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]), answer: tensor([316])
question: tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]), answer: tensor([215])
question: tensor([[ 1,  2,  3, 37, 38, 39, 40]]), answer: tensor([41])
question: tensor([[  1,   2,   3,   4,   5, 135]]), answer: tensor([136])
question: tensor([[ 78,  79, 150, 151,  14, 152, 153]]), answer: tensor([154])
question: tensor([[ 1,  2,  3, 92, 93, 94]]), answer: tensor([95])
question: tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]), answer: tensor([124])
question: tensor([[ 42,   2,   3, 274, 211, 275]]), answer: tensor([276])
question: tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]), answer: tensor([179])
question: tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]]), answer: tensor([6])
question: tensor([[10, 75, 76]]), answer: tensor([77])
question: tensor([[ 42, 250, 251, 118, 252, 253]]), answer: tensor([254])
question: tensor([[  1,   2,   3,   4,   5, 206]]), answer: tensor([207])
question: tensor([[  1,   2,   3,  69,   5, 155]]), answer: tensor([156])
question: tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]), answer: tensor([128])
question: tensor([[ 78,  79, 288,  81,  19,  14, 289]]), answer: tensor([85])
question: tensor([[10, 55,  3, 56,  5, 57]]), answer: tensor([58])
question: tensor([[ 1,  2,  3,  4,  5, 53]]), answer: tensor([54])
question: tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]), answer: tensor([36])
question: tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]), answer: tensor([185])
question: tensor([[  1,   2,   3,   4,   5, 109]]), answer: tensor([317])
question: tensor([[  1,   2,   3,   4,   5, 279]]), answer: tensor([280])
question: tensor([[42, 43, 44, 45, 46, 47, 48]]), answer: tensor([49])
question: tensor([[  1,   2,   3, 221,   5, 222, 223, 224]]), answer: tensor([225])
question: tensor([[42, 18,  2, 62, 63,  3, 64, 18]]), answer: tensor([65])
question: tensor([[  1,   2,   3,  37, 133,   5,  26]]), answer: tensor([134])
question: tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]), answer: tensor([52])
question: tensor([[ 10,  29, 130, 131]]), answer: tensor([132])
question: tensor([[10, 29,  3, 30, 31]]), answer: tensor([32])
question: tensor([[10, 11, 12, 13, 14, 15]]), answer: tensor([16])
question: tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]), answer: tensor([72])
question: tensor([[ 10,  11, 189, 158, 190]]), answer: tensor([191])
question: tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]), answer: tensor([295])
question: tensor([[10,  2,  3, 66,  5, 67]]), answer: tensor([68])
question: tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]), answer: tensor([106])
question: tensor([[ 1,  2,  3, 69,  5, 53]]), answer: tensor([260])
question: tensor([[ 42, 101,   2,   3,  17]]), answer: tensor([102])
question: tensor([[  1,   2,   3,   4,   5, 236, 237]]), answer: tensor([238])
question: tensor([[1, 2, 3, 4, 5, 8]]), answer: tensor([9])
question: tensor([[42, 86, 87, 88, 89, 39, 90]]), answer: tensor([91])
question: tensor([[ 1,  2,  3, 33, 34,  5, 35]]), answer: tensor([36])
question: tensor([[ 42,  18, 118,   3, 186, 187]]), answer: tensor([188])
question: tensor([[ 10,  75, 208]]), answer: tensor([209])
question: tensor([[ 42, 117, 118,   3, 119,  94, 120]]), answer: tensor([121])
question: tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]]), answer: tensor([307])
question: tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]]), answer: tensor([268])
question: tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]]), answer: tensor([220])
question: tensor([[  1,   2,   3, 180, 181, 182, 183]]), answer: tensor([184])
question: tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]), answer: tensor([194])
question: tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]]), answer: tensor([321])
question: tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]]), answer: tensor([273])
question: tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]), answer: tensor([23])
question: tensor([[ 42, 255,   2, 256,  83, 257, 258]]), answer: tensor([259])
question: tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]]), answer: tensor([113])
question: tensor([[ 42, 137, 118,   3, 247,   5, 248]]), answer: tensor([249])
question: tensor([[ 10,  75, 111]]), answer: tensor([112])
question: tensor([[  1,   2,   3, 163, 164, 165,  83,  84]]), answer: tensor([166])
question: tensor([[  1,   2,   3,   4,   5, 286]]), answer: tensor([287])
question: tensor([[ 42, 107,   2, 108,  19, 109]]), answer: tensor([110])
question: tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]), answer: tensor([61])
question: tensor([[ 10,  75,   3, 296,  19, 297]]), answer: tensor([298])
question: tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]]), answer: tensor([285])
question: tensor([[ 10,  11, 157, 158, 159]]), answer: tensor([160])
question: tensor([[  1,   2,   3,   4,   5, 113]]), answer: tensor([114])
question: tensor([[  1,   2,   3, 146, 147,  19, 148]]), answer: tensor([149])

In [45]:
len(dataloader)

90

In [42]:
import torch.nn as nn

In [47]:
class SimpleRNN(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()

    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn = nn.RNN(input_size=50, hidden_size=64, batch_first=True) #Input same as embedding_dim ig
    self.fc = nn.Linear(in_features=64, out_features=vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    hidden, final = self.rnn(embedded_question)
    output = self.fc(final.squeeze(0))


    return output

In [50]:
!pip install torchinfo
from torchinfo import summary

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [64]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("Shape of a: ", a.shape)

b = x(a)
print("Shape of b: ", b.shape)

c,d = y(b)
print("shape of c:", c.shape)
print("shape of d: ", d.shape)

e = z(d.squeeze(0))

print("shape of e: ", e.shape)

Shape of a:  torch.Size([1, 6])
Shape of b:  torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d:  torch.Size([1, 1, 64])
shape of e:  torch.Size([1, 324])

In [66]:
learning_rate = 0.001
epochs = 20

In [67]:
model = SimpleRNN(len(vocab))

In [68]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [69]:
# training loop

for epoch in range(epochs):

  total_loss = 0

  for question, answer in dataloader:

    optimizer.zero_grad()

    # forward pass
    output = model(question)

    # loss -> output shape (1,324) - (1)
    loss = criterion(output, answer[0])

    # gradients
    loss.backward()

    # update
    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch+1}, Loss: {total_loss:4f}")

Epoch: 1, Loss: 523.610247
Epoch: 2, Loss: 454.559391
Epoch: 3, Loss: 378.457108
Epoch: 4, Loss: 316.903921
Epoch: 5, Loss: 264.584342
Epoch: 6, Loss: 215.456879
Epoch: 7, Loss: 170.809186
Epoch: 8, Loss: 132.789889
Epoch: 9, Loss: 101.095114
Epoch: 10, Loss: 76.827672
Epoch: 11, Loss: 58.991031
Epoch: 12, Loss: 45.808988
Epoch: 13, Loss: 36.583895
Epoch: 14, Loss: 29.447548
Epoch: 15, Loss: 24.115584
Epoch: 16, Loss: 19.995111
Epoch: 17, Loss: 16.836260
Epoch: 18, Loss: 14.317162
Epoch: 19, Loss: 12.225659
Epoch: 20, Loss: 10.647782

In [70]:
def predict(model, question, threshold=0.5):

  # convert question to numbers
  numerical_question = text_to_indices(question, vocab)

  # tensor
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output = model(question_tensor)

  # convert logits to probs
  probs = torch.nn.functional.softmax(output, dim=1)

  # find index of max prob
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")

  print(list(vocab.keys())[index])

In [76]:
predict(model, "What is the capital of france?")

paris

In [72]:
list(vocab.keys())

['<UNK>',
 'what',
 'is',
 'the',
 'capital',
 'of',
 'france',
 'paris',
 'germany',
 'berlin',
 'who',
 'wrote',
 'to',
 'kill',
 'a',
 'mockingbird',
 'harper-lee',
 'largest',
 'planet',
 'in',
 'our',
 'solar',
 'system',
 'jupiter',
 'boiling',
 'point',
 'water',
 'celsius',
 '100',
 'painted',
 'mona',
 'lisa',
 'leonardo-da-vinci',
 'square',
 'root',
 '64',
 '8',
 'chemical',
 'symbol',
 'for',
 'gold',
 'au',
 'which',
 'year',
 'did',
 'world',
 'war',
 'ii',
 'end',
 '1945',
 'longest',
 'river',
 'nile',
 'japan',
 'tokyo',
 'developed',
 'theory',
 'relativity',
 'albert-einstein',
 'freezing',
 'fahrenheit',
 '32',
 'known',
 'as',
 'red',
 'mars',
 'author',
 '1984',
 'george-orwell',
 'currency',
 'united',
 'kingdom',
 'pound',
 'india',
 'delhi',
 'discovered',
 'gravity',
 'newton',
 'how',
 'many',
 'continents',
 'are',
 'there',
 'on',
 'earth',
 '7',
 'gas',
 'do',
 'plants',
 'use',
 'photosynthesis',
 'co2',
 'smallest',
 'prime',
 'number',
 '2',
 'invented',
 'telephone',
 'alexander-graham-bell',
 'australia',
 'canberra',
 'ocean',
 'pacific-ocean',
 'speed',
 'light',
 'vacuum',
 '299,792,458m/s',
 'language',
 'spoken',
 'brazil',
 'portuguese',
 'penicillin',
 'alexander-fleming',
 'canada',
 'ottawa',
 'mammal',
 'whale',
 'element',
 'has',
 'atomic',
 '1',
 'hydrogen',
 'tallest',
 'mountain',
 'everest',
 'city',
 'big',
 'apple',
 'newyork',
 'planets',
 'starry',
 'night',
 'vangogh',
 'formula',
 'h2o',
 'italy',
 'rome',
 'country',
 'famous',
 'sushi',
 'was',
 'first',
 'person',
 'step',
 'moon',
 'armstrong',
 'main',
 'ingredient',
 'guacamole',
 'avocado',
 'sides',
 'does',
 'hexagon',
 'have',
 '6',
 'china',
 'yuan',
 'pride',
 'and',
 'prejudice',
 'jane-austen',
 'iron',
 'fe',
 'hardest',
 'natural',
 'substance',
 'diamond',
 'continent',
 'by',
 'area',
 'asia',
 'president',
 'states',
 'george-washington',
 'bird',
 'its',
 'ability',
 'mimic',
 'sounds',
 'parrot',
 'longest-running',
 'animated',
 'tv',
 'show',
 'simpsons',
 'vaticancity',
 'most',
 'moons',
 'saturn',
 'romeo',
 'juliet',
 'shakespeare',
 'earths',
 'atmosphere',
 'nitrogen',
 'bones',
 'adult',
 'human',
 'body',
 '206',
 'metal',
 'liquid',
 'at',
 'room',
 'temperature',
 'mercury',
 'russia',
 'moscow',
 'electricity',
 'benjamin-franklin',
 'second-largest',
 'land',
 'color',
 'ripe',
 'banana',
 'yellow',
 'month',
 '28',
 'days',
 'common',
 'february',
 'study',
 'living',
 'organisms',
 'called',
 'biology',
 'home',
 'great',
 'wall',
 'bees',
 'collect',
 'from',
 'flowers',
 'nectar',
 'opposite',
 'day',
 'south',
 'korea',
 'seoul',
 'bulb',
 'edison',
 'humans',
 'breathe',
 'survival',
 'oxygen',
 '144',
 '12',
 'pyramids',
 'giza',
 'egypt',
 'sea',
 'creature',
 'eight',
 'arms',
 'octopus',
 'holiday',
 'celebrated',
 'december',
 '25',
 'christmas',
 'yen',
 'legs',
 'spider',
 'sport',
 'uses',
 'net,',
 'ball,',
 'hoop',
 'basketball',
 'kangaroos',
 'female',
 'minister',
 'uk',
 'margaretthatcher',
 'fastest',
 'animal',
 'cheetah',
 'periodic',
 'table',
 'spain',
 'madrid',
 'closest',
 'sun',
 'father',
 'computers',
 'charlesbabbage',
 'mexico',
 'mexicocity',
 'colors',
 'rainbow',
 'musical',
 'instrument',
 'black',
 'white',
 'keys',
 'piano',
 'americas',
 '1492',
 'christophercolumbus',
 'disney',
 'character',
 'long',
 'nose',
 'grows',
 'it',
 'when',
 'lying',
 'pinocchio',
 'directed',
 'movie',
 'titanic',
 'jamescameron',
 'superhero',
 'also',
 'dark',
 'knight',
 'batman',
 'brasilia',
 'fruit',
 'king',
 'fruits',
 'mango',
 'eiffel',
 'tower']